version: "3.7"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8181:8181"
    volumes:
      - .:/app
    depends_on:
      - db
    links: 
      - db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db/thedevconf
      - QUARKUS_DATASOURCE_DB_KIND=mysql
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=pass21782
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
  db:
    image: mysql:5.7
    container_name: tdc-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass21782
      - MYSQL_DATABASE=thedevconf