version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tdc-devenv-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lk01vtfrhoyk"
s3_prefix = "tdc-devenv-stack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
