create table Proposal (
    DTYPE varchar(31) not null,
    uuid varchar(255) not null,
    audienceLevel varchar(255),
    authorUUID varchar(255),
    demoLevel varchar(255),
    eventCode varchar(255),
    lang varchar(255),
    otherSpeakers varchar(255),
    privateMessage varchar(255),
    proposalCode varchar(255),
    pubAuth varchar(255),
    speaker varchar(255),
    speakerFirstName varchar(255),
    speakerName varchar(255),
    sponsor varchar(255),
    state varchar(255),
    summary varchar(255),
    title varchar(255),
    trackId varchar(255),
    trackLabel varchar(255),
    tracks varchar(255),
    typeId varchar(255),
    typeLabel varchar(255),
    primary key (uuid));
