(function(g){var window=this;'use strict';var lWa=function(a,b){return g.Se(a,b)},mWa=function(a,b){b=b instanceof g.Sf?b:g.$f(b,/^data:image\//i.test(b));
a.src=g.Tf(b)},Y6=function(a){g.ml(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},Z6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Jl(a.u,b,c)},nWa=function(a){if(a===g.Hp)throw Error("ES6 Iteration protocol does NOT adjust control flow when StopIteration is thrown from callback helper functions. If your code relies on this behavior, consider throwing a different error and catching it to terminate iteration.");
throw a;},oWa=function(a){if(a instanceof g.Fp)return a;
if("function"==typeof a.Mg)return a.Mg(!1);if(g.Ma(a)){var b=0,c=new g.Fp;c.next=function(){for(;;){if(b>=a.length)return g.j2;if(b in a)return g.Gp(a[b++]);b++}};
var d=c.next;c.Kj=function(){return g.Ip(d.call(c))};
return c}throw Error("Not implemented");},pWa=function(a,b,c){if(g.Ma(a))try{g.qc(a,b,c)}catch(e){nWa(e)}else for(a=oWa(a);;){var d=void 0;
try{d=a.Kj()}catch(e){if(e===g.Hp)break;throw e;}try{b.call(c,d,void 0,a)}catch(e){nWa(e)}}},qWa=function(a,b){var c=[];
pWa(b,function(d){try{var e=g.mx.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.yja(e)&&c.push(d)},a);
return c},rWa=function(a,b){qWa(a,b).forEach(function(c){g.mx.prototype.remove.call(this,c)},a)},sWa=function(a){if(a.xa){if(a.xa.locationOverrideToken)return{locationOverrideToken:a.xa.locationOverrideToken};
if(null!=a.xa.latitudeE7&&null!=a.xa.longitudeE7)return{latitudeE7:a.xa.latitudeE7,longitudeE7:a.xa.longitudeE7}}return null},tWa=function(a,b){g.Zb(a,b)||a.push(b)},$6=function(a){var b=0,c;
for(c in a)b++;return b},uWa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},a7=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return uWa(a)},vWa=function(a,b,c,d){var e=new g.el(null,void 0);
a&&g.fl(e,a);b&&g.gl(e,b);c&&g.hl(e,c);d&&(e.K=d);return e},b7=function(a,b){g.du[a]=!0;
var c=g.bu();c&&c.publish.apply(c,arguments);g.du[a]=!1},c7=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.qt;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",wWa(this,a.capabilities||""),xWa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},wWa=function(a,b){a.capabilities.clear();
g.hq(b.split(","),g.Qa(lWa,yWa)).forEach(function(c){a.capabilities.add(c)})},xWa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},d7=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},e7=function(a,b){return!!b&&(a.id==b||a.uuid==b)},zWa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},AWa=function(a){return new d7(a)},BWa=function(a){return Array.isArray(a)?g.Un(a,AWa):[]},f7=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},g7=function(a){return Array.isArray(a)?"["+g.Un(a,f7).join(",")+"]":"null"},h7=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},CWa=function(a){return g.Un(a,function(b){return{key:b.id,
name:b.name}})},i7=function(a,b){return g.Vb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},j7=function(a,b){return g.Vb(a,function(c){return e7(c,b)})},DWa=function(){var a=(0,g.Oy)();
a&&rWa(a,a.i.Mg(!0))},k7=function(){var a=g.Ry("yt-remote-connected-devices")||[];
g.nc(a);return a},EWa=function(a){if(g.$b(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Un(a,function(d,e){return 0==e?d:d.substring(c.length)})},FWa=function(a){g.Qy("yt-remote-connected-devices",a,86400)},m7=function(){if(l7)return l7;
var a=g.Ry("yt-remote-device-id");a||(a=h7(),g.Qy("yt-remote-device-id",a,31536E3));for(var b=k7(),c=1,d=a;g.Zb(b,d);)c++,d=a+"#"+c;return l7=d},n7=function(){var a=k7(),b=m7();
g.Zb(a,b);g.Ty()&&g.pc(a,b);a=EWa(a);if(g.$b(a))try{g.fja("remote_sid")}catch(c){}else try{g.Ju("remote_sid",a.join(","),-1)}catch(c){}},GWa=function(){return g.Ry("yt-remote-session-browser-channel")},HWa=function(){return g.Ry("yt-remote-local-screens")||[]},IWa=function(){g.Qy("yt-remote-lounge-token-expiration",!0,86400)},JWa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Un(HWa(),function(d){return d.loungeToken}),c=g.Un(a,function(d){return d.loungeToken});
g.Vn(c,function(d){return!g.Zb(b,d)})&&IWa();
g.Qy("yt-remote-local-screens",a,31536E3)},KWa=function(a,b){g.Qy("yt-remote-session-browser-channel",a);
g.Qy("yt-remote-session-screen-id",b);a=k7();b=m7();g.Zb(a,b)||a.push(b);FWa(a);n7()},o7=function(a){a||(g.Sy("yt-remote-session-screen-id"),g.Sy("yt-remote-session-video-id"));
n7();a=k7();g.cc(a,m7());FWa(a)},LWa=function(){if(!p7){var a=g.av();
a&&(p7=new g.Qu(a))}},MWa=function(){LWa();
return p7?!!p7.get("yt-remote-use-staging-server"):!1},q7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},NWa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},OWa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},r7=function(a){a.length?PWa(a.shift(),function(){r7(a)}):s7()},QWa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},PWa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.zk(d,g.xs(a));(document.head||document.documentElement).appendChild(d)},RWa=function(){var a=q7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},s7=function(){var a=OWa();
a&&a(!1,"No cast extension found")},t7=function(){if(SWa){var a=2,b=OWa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;PWa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",s7,c)}},TWa=function(){t7();
var a=RWa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},VWa=function(){t7();
var a=RWa();a.push.apply(a,g.u(UWa.map(QWa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},u7=function(a,b,c){g.G.call(this);
this.I=null!=c?(0,g.E)(a,c):a;this.Wf=b;this.D=(0,g.E)(this.cR,this);this.i=!1;this.u=0;this.B=this.Nb=null;this.C=[]},v7=function(a,b,c){g.G.call(this);
this.C=null!=c?a.bind(c):a;this.Wf=b;this.B=null;this.i=!1;this.u=0;this.Nb=null},w7=function(a){a.Nb=g.ei(function(){a.Nb=null;
a.i&&!a.u&&(a.i=!1,w7(a))},a.Wf);
var b=a.B;a.B=null;a.C.apply(null,b)},x7=function(){},y7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},A7=function(a){z7.dispatchEvent(new WWa(z7,a))},WWa=function(a,b){g.ye.call(this,"statevent",a);
this.stat=b},B7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.Kl(this);this.I=new g.di;this.I.setInterval(250)},YWa=function(a,b,c){a.Xt=1;
a.qn=Y6(b.clone());a.Eq=c;a.D=!0;XWa(a,null)},C7=function(a,b,c,d,e){a.Xt=1;
a.qn=Y6(b.clone());a.Eq=null;a.D=c;e&&(a.gO=!1);XWa(a,d)},XWa=function(a,b){a.Jt=Date.now();
D7(a);a.Qo=a.qn.clone();Z6(a.Qo,"t",a.K);a.JB=0;a.Lf=a.i.FD(a.i.yx()?b:null);0<a.vC&&(a.XA=new v7((0,g.E)(a.mP,a,a.Lf),a.vC));a.C.Ra(a.Lf,"readystatechange",a.dR);b=a.ip?g.Ze(a.ip):{};a.Eq?(a.HB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Lf.send(a.Qo,a.HB,a.Eq,b)):(a.HB="GET",a.gO&&!g.fh&&(b.Connection="close"),a.Lf.send(a.Qo,a.HB,null,b));a.i.Lj(1)},$Wa=function(a,b){var c=a.JB,d=b.indexOf("\n",c);
if(-1==d)return E7;c=Number(b.substring(c,d));if(isNaN(c))return ZWa;d+=1;if(d+c>b.length)return E7;b=b.substr(d,c);a.JB=d+c;return b},bXa=function(a,b){a.Jt=Date.now();
D7(a);var c=b?window.location.hostname:"";a.Qo=a.qn.clone();g.ml(a.Qo,"DOMAIN",c);g.ml(a.Qo,"t",a.K);try{a.Xj=new ActiveXObject("htmlfile")}catch(m){F7(a);a.cn=7;A7(22);G7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in H7)f=H7[f];else if(f in aXa)f=H7[f]=aXa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
H7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.og(g.Kf("b/12014412"),d);a.Xj.open();a.Xj.write(g.kg(c));a.Xj.close();a.Xj.parentWindow.m=(0,g.E)(a.UW,a);a.Xj.parentWindow.d=(0,g.E)(a.qN,a,!0);a.Xj.parentWindow.rpcClose=(0,g.E)(a.qN,a,!1);c=a.Xj.createElement("DIV");a.Xj.parentWindow.document.body.appendChild(c);d=g.Zf(a.Qo.toString());d=g.Fg(g.Tf(d));d=g.og(g.Kf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.qg(c,d);a.i.Lj(1)},D7=function(a){a.zH=Date.now()+
a.u;
cXa(a,a.u)},cXa=function(a,b){if(null!=a.uu)throw Error("WatchDog timer not null");
a.uu=y7((0,g.E)(a.bX,a),b)},I7=function(a){a.uu&&(g.C.clearTimeout(a.uu),a.uu=null)},G7=function(a){a.i.vf()||a.Cp||a.i.py(a)},F7=function(a){I7(a);
g.ve(a.XA);a.XA=null;a.I.stop();g.Ml(a.C);if(a.Lf){var b=a.Lf;a.Lf=null;b.abort();b.dispose()}a.Xj&&(a.Xj=null)},J7=function(a,b){try{a.i.jN(a,b),a.i.Lj(4)}catch(c){}},eXa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;dXa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){eXa(a,b,c,d,f)},f)})}},dXa=function(a,b,c){var d=new Image;
d.onload=function(){try{K7(d),c(!0)}catch(e){}};
d.onerror=function(){try{K7(d),c(!1)}catch(e){}};
d.onabort=function(){try{K7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
mWa(d,a)},K7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},fXa=function(a){this.i=a;
this.u=new x7},gXa=function(a){var b=L7(a.i,a.Yu,"/mail/images/cleardot.gif");
Y6(b);eXa(b.toString(),5E3,(0,g.E)(a.PR,a),3,2E3);a.Lj(1)},N7=function(a){var b=a.i.X;
if(null!=b)A7(5),b?(A7(11),M7(a.i,a,!1)):(A7(12),M7(a.i,a,!0));else if(a.uh=new B7(a,void 0,void 0,void 0),a.uh.ip=a.wC,b=a.i,b=L7(b,b.yx()?a.Pu:null,a.xC),A7(5),!g.Gc||g.zc(10))Z6(b,"TYPE","xmlhttp"),C7(a.uh,b,!1,a.Pu,!1);else{Z6(b,"TYPE","html");var c=a.uh;a=!!a.Pu;c.Xt=3;c.qn=Y6(b.clone());bXa(c,a)}},O7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new x7;this.S=a||null;this.X=null!=b?b:null;this.I=c||!1},hXa=function(a,b){this.i=a;
this.map=b;this.context=null},iXa=function(a,b,c,d){g.ye.call(this,"timingevent",a);
this.size=b;this.mx=d},jXa=function(a){g.ye.call(this,"serverreachability",a)},mXa=function(a){kXa(a);
if(3==a.i){var b=a.Cw++,c=a.ez.clone();g.ml(c,"SID",a.B);g.ml(c,"RID",b);g.ml(c,"TYPE","terminate");P7(a,c);b=new B7(a,a.B,b,void 0);b.Xt=2;b.qn=Y6(c.clone());mWa(new Image,b.qn.toString());b.Jt=Date.now();D7(b)}lXa(a)},nXa=function(a){a.oS(1,0);
a.ez=L7(a,null,a.yC);Q7(a)},kXa=function(a){a.yn&&(a.yn.abort(),a.yn=null);
a.Me&&(a.Me.cancel(),a.Me=null);a.Ol&&(g.C.clearTimeout(a.Ol),a.Ol=null);R7(a);a.Xg&&(a.Xg.cancel(),a.Xg=null);a.Jn&&(g.C.clearTimeout(a.Jn),a.Jn=null)},oXa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new hXa(a.TT++,b));2!=a.i&&3!=a.i||Q7(a)},pXa=function(a){var b=0;
a.Me&&b++;a.Xg&&b++;return b},Q7=function(a){a.Xg||a.Jn||(a.Jn=y7((0,g.E)(a.oN,a),0),a.Es=0)},rXa=function(a,b){if(1==a.i){if(!b){a.Cw=Math.floor(1E5*Math.random());
b=a.Cw++;var c=new B7(a,"",b,void 0);c.ip=a.pk;var d=S7(a),e=a.ez.clone();g.ml(e,"RID",b);g.ml(e,"CVER","1");P7(a,e);YWa(c,e,d);a.Xg=c;a.i=2}}else 3==a.i&&(b?qXa(a,b):0==a.u.length||a.Xg||qXa(a))},qXa=function(a,b){if(b)if(6<a.Dp){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Cw-1;b=S7(a)}else c=b.S,b=b.Eq;else c=a.Cw++,b=S7(a);var d=a.ez.clone();g.ml(d,"SID",a.B);g.ml(d,"RID",c);g.ml(d,"AID",a.Zs);P7(a,d);c=new B7(a,a.B,c,a.Es+1);c.ip=a.pk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Xg=c;YWa(c,d,b)},P7=function(a,b){a.Mf&&(a=a.Mf.GK())&&g.Ie(a,function(c,d){g.ml(b,d,c)})},S7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Dp&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={jr:e.jr},f++){e.jr=a.u[f].i;var h=a.u[f].map;e.jr=6>=a.Dp?f:e.jr-d;try{g.Ie(h,function(l){return function(m,n){c.push("req"+l.jr+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.jr+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},sXa=function(a){a.Me||a.Ol||(a.K=1,a.Ol=y7((0,g.E)(a.nN,a),0),a.Yr=0)},T7=function(a){if(a.Me||a.Ol||3<=a.Yr)return!1;
a.K++;a.Ol=y7((0,g.E)(a.nN,a),tXa(a,a.Yr));a.Yr++;return!0},M7=function(a,b,c){a.FB=c;
a.qk=b.El;a.I||nXa(a)},R7=function(a){null!=a.Lp&&(g.C.clearTimeout(a.Lp),a.Lp=null)},tXa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U7=function(a,b){if(2==b||9==b){var c=null;
a.Mf&&(c=null);var d=(0,g.E)(a.eY,a);c||(c=new g.el("//www.google.com/images/cleardot.gif"),Y6(c));dXa(c.toString(),1E4,d)}else A7(2);uXa(a,b)},uXa=function(a,b){a.i=0;
a.Mf&&a.Mf.TJ(b);lXa(a);kXa(a)},lXa=function(a){a.i=0;
a.qk=-1;if(a.Mf)if(0==a.C.length&&0==a.u.length)a.Mf.rD();else{g.fc(a.C);var b=g.fc(a.u);a.C.length=0;a.u.length=0;a.Mf.rD(b)}},L7=function(a,b,c){var d=g.Fl(c);
if(""!=d.i)b&&g.gl(d,b+"."+d.i),g.hl(d,d.B);else{var e=window.location;d=vWa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Fv&&g.Ie(a.Fv,function(f,h){g.ml(d,h,f)});
g.ml(d,"VER",a.Dp);P7(a,d);return d},vXa=function(){},wXa=function(){this.i=[];
this.u=[]},xXa=function(a,b){this.action=a;
this.params=b||{}},V7=function(a,b){g.G.call(this);
this.i=new g.Q(this.LW,0,this);g.I(this,this.i);this.Wf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.E)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.E)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},W7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.I=b;this.B=new g.au;this.u=new V7(this.GX,this);this.i=null;this.Z=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.oa=d;this.Ba=e},yXa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.FB,sessionId:a.i.B,arrayId:a.i.Zs}},zXa=function(a,b){a.S=b||0;
a.u.stop();X7(a);a.i&&(3==a.i.getState()&&rXa(a.i),mXa(a.i));a.S=0},Y7=function(a){return!!a.i&&3==a.i.getState()},X7=function(a){if(a.i){var b=a.oa(),c=a.i.pk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.pk=c}},Z7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Wi(4,a))||"";b&&(this.port=":"+b);this.domain=g.Xi(a)||"";a=g.vb();0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.ub(a,"10.0")&&(this.u=!1))},$7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.hj(c+b,{})},a8=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.C,d,!0),onError:g.Qa(a.B,e),onTimeout:g.Qa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Lt(b,a)},DXa=function(){var a=AXa;
BXa();b8.push(a);CXa()},c8=function(a,b){BXa();
var c=EXa(a,String(b));g.$b(b8)?FXa(c):(CXa(),g.qc(b8,function(d){d(c)}))},BXa=function(){b8||(b8=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",b8,void 0))},FXa=function(a){var b=(d8+1)%50;
d8=b;e8[b]=a;f8||(f8=49==b)},CXa=function(){var a=b8;
if(e8[0]){var b=f8?d8:-1;do{b=(b+1)%50;var c=e8[b];g.qc(a,function(d){d(c)})}while(b!=d8);
e8=Array(50);d8=-1;f8=!1}},EXa=function(a,b){var c=(Date.now()-GXa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g8=function(a){g.ky.call(this);
this.I=a;this.screens=[]},HXa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},IXa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.hq(a.screens,function(f){return!!i7(b,f)});
for(var d=0,e=b.length;d<e;d++)c=HXa(a,b[d])||c;return c},JXa=function(a,b){var c=a.screens.length;
a.screens=g.hq(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},h8=function(a,b,c,d,e){g.ky.call(this);
this.B=a;this.K=b;this.C=c;this.I=d;this.D=e;this.u=0;this.i=null;this.Nb=NaN},j8=function(a){g8.call(this,"LocalScreenService");
this.u=a;this.i=NaN;i8(this);this.info("Initializing with "+g7(this.screens))},KXa=function(a){if(a.screens.length){var b=g.Un(a.screens,function(d){return d.id}),c=$7(a.u,"/pairing/get_lounge_token_batch");
a8(a.u,c,{screen_ids:b.join(",")},(0,g.E)(a.PS,a),(0,g.E)(a.OS,a))}},i8=function(a){if(g.M("deprecate_pair_servlet_enabled"))return IXa(a,[]);
var b=BWa(HWa());b=g.hq(b,function(c){return!c.uuid});
return IXa(a,b)},k8=function(a,b){JWa(g.Un(a.screens,zWa));
b&&IWa()},m8=function(a,b){g.ky.call(this);
this.I=b;b=(b=g.Ry("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.Zb(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;l8("Initialized with "+g.Ni(this.i))},n8=function(a,b,c){var d=$7(a.D,"/pairing/get_screen_availability");
a8(a.D,d,{lounge_token:b.token},(0,g.E)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.E)(function(){c(!1)},a))},o8=function(a,b){a:if($6(b)!=$6(a.i))var c=!1;
else{c=g.Qe(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(l8("Updated online screens: "+g.Ni(a.i)),a.i=b,a.ea("screenChange"));LXa(a)},p8=function(a){isNaN(a.B)||g.Ss(a.B);
a.B=g.Qs((0,g.E)(a.rG,a),0<a.C&&a.C<g.Sa()?2E4:1E4)},l8=function(a){c8("OnlineScreenService",a)},MXa=function(a){var b={};
g.qc(a.I(),function(c){c.token?b[c.token]=c.id:this.oe("Requesting availability of screen w/o lounge token.")});
return b},LXa=function(a){a=g.Qe(g.Je(a.i,function(b){return b}));
g.nc(a);a.length?g.Qy("yt-remote-online-screen-ids",a.join(","),60):g.Sy("yt-remote-online-screen-ids")},q8=function(a,b){b=void 0===b?!1:b;
g8.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};NXa(this)},PXa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Ih(),l=c?j7(h,c):null;c&&(a.K||l)||(l=j7(h,b));if(l){l.uuid=b;var m=r8(a,l);n8(a.i,m,function(n){e(n?m:null)})}else c?OXa(a,c,(0,g.E)(function(n){var p=r8(this,new d7({name:d,
screenId:c,loungeToken:n,dialId:b||""}));n8(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},QXa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},RXa=function(a,b,c){n8(a.i,b,c)},OXa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Lt($7(a.C,"/pairing/get_lounge_token_batch"),e)},SXa=function(a){a.screens=a.u.Ih();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+g7(a.screens))},NXa=function(a){s8(a);
a.u=new j8(a.C);a.u.subscribe("screenChange",(0,g.E)(a.ZS,a));SXa(a);a.K||(a.B=BWa(g.Ry("yt-remote-automatic-screen-cache")||[]));s8(a);a.info("Initializing automatic screens: "+g7(a.B));a.i=new m8(a.C,(0,g.E)(a.Ih,a,!0));a.i.subscribe("screenChange",(0,g.E)(function(){this.ea("onlineScreenChange")},a))},r8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=j7(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||TXa(a));s8(a);a.D[b.uuid]=b.id;g.Qy("yt-remote-device-id-map",a.D,31536E3);return b},TXa=function(a){a=g.hq(a.B,function(b){return"shortLived"!=b.idType});
g.Qy("yt-remote-automatic-screen-cache",g.Un(a,zWa))},s8=function(a){a.D=g.Ry("yt-remote-device-id-map")||{}},t8=function(a,b,c){g.ky.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},u8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},UXa=function(a,b){a.C&&(a.C.token=b,r8(a.B,a.C));
a.ea("sessionScreen",a.C)},v8=function(a,b){c8(a.Ba,b)},w8=function(a,b,c){t8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.oa=(0,g.E)(this.iR,this);this.Aa=(0,g.E)(this.fX,this);this.Z=g.Qs(function(){VXa(d,null)},12E4);
this.K=this.D=this.I=this.S=0;this.xa=!1;this.X="unknown"},x8=function(a,b){g.Ss(a.K);
a.K=0;0==b?WXa(a):a.K=g.Qs(function(){WXa(a)},b)},WXa=function(a){XXa(a,"getLoungeToken");
g.Ss(a.D);a.D=g.Qs(function(){YXa(a,null)},3E4)},XXa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Ni(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.E)(function(){v8(this,"Failed to send message: "+b+".")},a)):v8(a,"Sending yt message without session: "+g.Ni(c))},y8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.UK(b,function(c){u8(a,c)},function(){return a.Ag()},5)):a.Ag(Error("Waiting for session status timed out."))},$Xa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);ZXa(a,d,function(e){e?(a.xa=!0,r8(a.B,d),u8(a,d),a.X="unknown",x8(a,c)):(g.Bs(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Ag())},5)},VXa=function(a,b){g.Ss(a.Z);
a.Z=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?$Xa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Bs(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),y8(a,b.screenId))):(g.Bs(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),y8(a,b.screenId)):y8(a,b.screenId):a.Ag(Error("Waiting for session status timed out."))},YXa=function(a,b){g.Ss(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,x8(a,3E4)):(UXa(a,b.loungeToken),a.xa=!1,a.X="unknown",x8(a,b.loungeTokenRefreshIntervalMs))},ZXa=function(a,b,c,d){g.Ss(a.I);
a.I=0;RXa(a.B,b,function(e){e||0>d?c(e):a.I=g.Qs(function(){ZXa(a,b,c,d-1)},300)})},aYa=function(a){g.Ss(a.S);
a.S=0;g.Ss(a.I);a.I=0;g.Ss(a.Z);a.Z=0;g.Ss(a.D);a.D=0;g.Ss(a.K);a.K=0},z8=function(a,b,c,d){t8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.La=c;this.Ka=null;this.Z=g.Ia;this.X=NaN;this.Ia=(0,g.E)(this.jR,this);this.D=g.Ia;this.K=this.I=0;this.oa=!1;this.xa="unknown"},A8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},bYa=function(a){a.D=a.B.DI(a.Aa,a.i.label,a.i.friendlyName,A8(a),function(b,c){a.D=g.Ia;
a.oa=!0;u8(a,b);"shortLived"==b.idType&&0<c&&B8(a,c)},function(b){a.D=g.Ia;
a.Ag(b)})},cYa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.La;MWa()&&(b.env_useStageMdx=1);return g.fj(b)},C8=function(a){return new Promise(function(b){a.Aa=h7();
if(a.Ka){var c=new chrome.cast.DialLaunchResponse(!0,cYa(a));b(c);bYa(a)}else a.Z=function(){g.Ss(a.X);a.Z=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,cYa(a));b(d);bYa(a)},a.X=g.Qs(function(){a.Z()},100)})},eYa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);return(new Promise(function(e){dYa(a,d,function(f){f?(a.oa=!0,r8(a.B,d),u8(a,d),B8(a,c)):g.Bs(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):C8(a)})},fYa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){PXa(a.B,c,b,d,function(f){f&&f.token&&u8(a,f);e(f)},function(f){v8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):C8(a)})},dYa=function(a,b,c,d){g.Ss(a.I);
a.I=0;RXa(a.B,b,function(e){e||0>d?c(e):a.I=g.Qs(function(){dYa(a,b,c,d-1)},300)})},B8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
A8(a)&&(g.Ss(a.K),a.K=0,0==b?gYa(a):a.K=g.Qs(function(){gYa(a)},b))},gYa=function(a){A8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,B8(a,3E4)):(a.oa=!1,a.xa="unknown",UXa(a,b.loungeToken),B8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";B8(a,3E4)})},hYa=function(a){g.Ss(a.I);
a.I=0;g.Ss(a.K);a.K=0;a.D();a.D=function(){};
g.Ss(a.X)},D8=function(a,b){t8.call(this,a,b,"ManualSession");
this.u=g.Qs((0,g.E)(this.gt,this,null),150)},E8=function(a,b){g.ky.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.I=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.E)(this.XV,this)},iYa=function(a,b){return b?g.Vb(a.B,function(c){return e7(b,c.label)},a):null},F8=function(a){c8("Controller",a)},AXa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G8=function(a){return a.K||!!a.B.length||!!a.i},H8=function(a,b,c){b!=a.i&&(g.ve(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.E)(a.mN,a,b)),b.subscribe("sessionFailed",function(){return jYa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.gt(null)):a.ea("yt-remote-cast2-session-change",null))},jYa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},kYa=function(a){var b=a.u.CI(),c=a.i&&a.i.i;
a=g.Un(b,function(d){c&&e7(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=iYa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},pYa=function(a,b,c,d){d.disableCastApi?I8("Cannot initialize because disabled by Mdx config."):lYa()?mYa(b,d)&&(J8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?nYa(a,c):(window.__onGCastApiAvailable=function(e,f){e?nYa(a,c):(K8("Failed to load cast API: "+f),L8(!1),J8(!1),g.Sy("yt-remote-cast-available"),g.Sy("yt-remote-cast-receiver"),
oYa(),c(!1))},d.loadCastApiSetupScript?g.Uy("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=q7()&&TWa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?s7():89<=q7()?VWa():(t7(),r7(UWa.map(QWa))))):I8("Cannot initialize because not running Chrome")},oYa=function(){I8("dispose");
var a=M8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);qYa(!1);g.gu(N8);N8.length=0},O8=function(){return!!g.Ry("yt-remote-cast-installed")},rYa=function(){var a=g.Ry("yt-remote-cast-receiver");
return a?a.friendlyName:null},sYa=function(){I8("clearCurrentReceiver");
g.Sy("yt-remote-cast-receiver")},tYa=function(){return O8()?M8()?M8().getCastSession():(K8("getCastSelector: Cast is not initialized."),null):(K8("getCastSelector: Cast API is not installed!"),null)},Q8=function(){O8()?M8()?P8()?(I8("Requesting cast selector."),M8().requestSession()):(I8("Wait for cast API to be ready to request the session."),N8.push(g.fu("yt-remote-cast2-api-ready",Q8))):K8("requestCastSelector: Cast is not initialized."):K8("requestCastSelector: Cast API is not installed!")},R8=
function(a,b){P8()?M8().setConnectedScreenStatus(a,b):K8("setConnectedScreenStatus called before ready.")},lYa=function(){var a=0<=g.vb().search(/ (CrMo|Chrome|CriOS)\//);
return g.vA||a},uYa=function(a,b){M8().init(a,b)},mYa=function(a,b){var c=!1;
M8()||(a=new E8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Qy("yt-remote-cast-available",d);b7("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){I8("onReceiverSelected: "+d.friendlyName);
g.Qy("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){I8("onReceiverResumed: "+d.friendlyName);
g.Qy("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){I8("onSessionChange: "+f7(d));
d||g.Sy("yt-remote-cast-receiver");b7("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
I8("cloudview.createSingleton_: "+c);return c},M8=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},nYa=function(a,b){L8(!0);
J8(!1);uYa(a,function(c){c?(qYa(!0),g.hu("yt-remote-cast2-api-ready")):(K8("Failed to initialize cast API."),L8(!1),g.Sy("yt-remote-cast-available"),g.Sy("yt-remote-cast-receiver"),oYa());b(c)})},I8=function(a){c8("cloudview",a)},K8=function(a){c8("cloudview",a)},L8=function(a){I8("setCastInstalled_ "+a);
g.Qy("yt-remote-cast-installed",a)},P8=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},qYa=function(a){I8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},S8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.trackData=null;this.hasNext=this.Rk=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},T8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Rk=!1;a.hasNext=!1;a.K=0;a.I=g.Sa();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},U8=function(a){return a.Hc()?(g.Sa()-a.I)/1E3:0},V8=function(a,b){a.K=b;
a.I=g.Sa()},W8=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},X8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T8(a)},Y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$e(a.trackData);b.hasPrevious=a.Rk;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},$8=function(a,b){g.ky.call(this);
this.B=0;this.C=a;this.I=[];this.D=new wXa;this.u=this.i=null;this.X=(0,g.E)(this.FU,this);this.K=(0,g.E)(this.Lw,this);this.S=(0,g.E)(this.EU,this);this.Z=(0,g.E)(this.MU,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.HG,this),vYa(this))):c=3;0!=c&&(b?this.HG(c):g.Qs((0,g.E)(function(){this.HG(c)},this),0));
(a=tYa())&&Z8(this,a);this.subscribe("yt-remote-cast2-session-change",this.Z)},a9=function(a){return new S8(a.C.getPlayerContextData())},vYa=function(a){g.qc("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.I.push(this.C.subscribe(b,g.Qa(this.VV,b),this))},a)},wYa=function(a){g.qc(a.I,function(b){this.C.unsubscribeByKey(b)},a);
a.I.length=0},b9=function(a){return 1==a.getState()},c9=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},e9=function(a,b,c){var d=a9(a);
V8(d,c);-1E3!=d.playerState&&(d.playerState=b);d9(a,d)},f9=function(a,b,c){a.C.sendMessage(b,c)},d9=function(a,b){wYa(a);
a.C.setPlayerContextData(Y8(b));vYa(a)},Z8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.Lw(null));
a.u=b;a.u&&(c8("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.Lw(a.u.media[0]))},xYa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=a9(a);b.contentId!=d.videoId&&c8("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V8(d,a.i.getEstimatedTime());d9(a,d)}else c8("CP","No cast media video. Ignoring state update.")},g9=function(a,b,c){return(0,g.E)(function(d){this.oe("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.oe("Retrying "+b+" using MDx browser channel."),f9(this,b,c))},a)},h9=function(a,b,c,d){d=void 0===d?!1:d;
g.ky.call(this);this.D=NaN;this.xa=!1;this.S=this.K=this.Z=this.oa=NaN;this.X=[];this.C=this.I=this.B=this.wc=this.i=null;this.Ia=a;this.Ba=d;this.X.push(g.Gs(window,"beforeunload",(0,g.E)(this.KS,this)));this.u=[];this.wc=new S8;this.Ka=b.id;this.Aa=b.idType;this.i=yYa(this,c);this.i.subscribe("handlerOpened",this.JU,this);this.i.subscribe("handlerClosed",this.GU,this);this.i.subscribe("handlerError",this.HU,this);this.i.subscribe("handlerMessage",this.IU,this);this.i.jB(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.wc.videoId;g.Ty()&&g.Qy("yt-remote-session-video-id",e)},this)},zYa=function(a){return g.Vb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},i9=function(a){c8("conn",a)},yYa=function(a,b){return new W7($7(a.Ia,"/bc"),b,!1,function(){return a.II()},"shortLived"==a.Aa)},j9=function(a,b){a.ea("proxyStateChange",b)},AYa=function(a){a.D=g.Qs((0,g.E)(function(){i9("Connecting timeout");
this.As(1)},a),2E4)},k9=function(a){g.Ss(a.D);
a.D=NaN},l9=function(a){g.Ss(a.oa);
a.oa=NaN},BYa=function(a){m9(a);
a.Z=g.Qs((0,g.E)(function(){n9(this,"getNowPlaying")},a),2E4)},m9=function(a){g.Ss(a.Z);
a.Z=NaN},DYa=function(a,b){var c=null;
if(b){var d=zYa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ga("yt.mdx.remote.remoteClient_",c,void 0);b&&(k9(a),l9(a));c=Y7(a.i)&&isNaN(a.D);b==c?b&&(j9(a,1),n9(a,"getSubtitlesTrack")):b?(a.TK()&&a.wc.reset(),j9(a,1),n9(a,"getNowPlaying"),CYa(a)):a.As(1)},EYa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.wc.videoId&&(g.Ve(b.params)?a.wc.trackData=null:a.wc.trackData=b.params,a.ea("remotePlayerChange"))},FYa=function(a,b,c){var d=b.params.videoId||b.params.video_id,e=parseInt(b.params.currentIndex,10);
a.wc.listId=b.params.listId||a.wc.listId;X8(a.wc,d,e);a.ea("remoteQueueChange",c)},HYa=function(a,b){b.params=b.params||{};
FYa(a,b,"NOW_PLAYING_MAY_CHANGE");GYa(a,b);a.ea("autoplayDismissed")},GYa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V8(a.wc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.wc.playerState&&(c=-1E3);a.wc.playerState=c;c=Number(b.params.loadedTime);a.wc.S=isNaN(c)?0:c;a.wc.Tj(Number(b.params.duration));c=a.wc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.wc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.wc.playerState?BYa(a):m9(a);a.ea("remotePlayerChange")},IYa=function(a,b){if(-1E3!=a.wc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.wc.playerState=c;b=parseInt(b.params.currentTime,10);V8(a.wc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},JYa=function(a,b){var c="true"==b.params.muted;
a.wc.volume=parseInt(b.params.volume,10);a.wc.muted=c;a.ea("remotePlayerChange")},KYa=function(a,b){a.I=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},LYa=function(a,b){var c="true"==b.params.hasNext;
a.wc.Rk="true"==b.params.hasPrevious;a.wc.hasNext=c;a.ea("previousNextChange")},CYa=function(a){g.Ss(a.S);
a.S=g.Qs((0,g.E)(a.As,a,1),864E5)},n9=function(a,b,c){c?i9("Sending: action="+b+", params="+g.Ni(c)):i9("Sending: action="+b);
a.i.sendMessage(b,c)},o9=function(a){g8.call(this,"ScreenServiceProxy");
this.Ue=a;this.i=[];this.i.push(this.Ue.$_s("screenChange",(0,g.E)(this.nR,this)));this.i.push(this.Ue.$_s("onlineScreenChange",(0,g.E)(this.BV,this)))},PYa=function(a,b){LWa();
if(!p7||!p7.get("yt-remote-disable-remote-module-for-dev")){b=g.L("MDX_CONFIG")||b;DWa();n7();p9||(p9=new Z7(b?b.loungeApiHost:void 0),MWa()&&(p9.i="/api/loungedev"));q9||(q9=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",q9,void 0));MYa();var c=r9();if(!c){var d=new q8(p9,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=r9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Ga("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);pYa(a,d,function(f){f?s9()&&R8(s9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){b7("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),t9("Initializing: "+
g.Ni(b)),u9.push(g.fu("yt-remote-cast2-api-ready",function(){b7("yt-remote-api-ready")})),u9.push(g.fu("yt-remote-cast2-availability-change",function(){b7("yt-remote-receiver-availability-change")})),u9.push(g.fu("yt-remote-cast2-receiver-selected",function(){v9(null);
b7("yt-remote-auto-connect","cast-selector-receiver")})),u9.push(g.fu("yt-remote-cast2-receiver-resumed",function(){b7("yt-remote-receiver-resumed","cast-selector-receiver")})),u9.push(g.fu("yt-remote-cast2-session-change",NYa)),u9.push(g.fu("yt-remote-connection-change",function(f){f?R8(s9(),"YouTube TV"):w9()||(R8(null,null),sYa())})),u9.push(g.fu("yt-remote-cast2-session-failed",function(){b7("yt-remote-connection-failed")})),a=x9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.M("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),t9(" -- with channel params: "+g.Ni(a)),a?(g.Qy("yt-remote-session-app",a.app),g.Qy("yt-remote-session-name",a.name)):(g.Sy("yt-remote-session-app"),g.Sy("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),s9()||OYa())}},QYa=function(){var a=r9().Ue.$_gos();
var b=y9();b&&z9()&&(i7(a,b)||a.push(b));return CWa(a)},A9=function(){var a=RYa();
!a&&O8()&&rYa()&&(a={key:"cast-selector-receiver",name:rYa()});return a},RYa=function(){var a=QYa(),b=y9();
b||(b=w9());return g.Vb(a,function(c){return b&&e7(b,c.key)?!0:!1})},y9=function(){var a=s9();
if(!a)return null;var b=r9().Ih();return j7(b,a)},NYa=function(a){t9("remote.onCastSessionChange_: "+f7(a));
if(a){var b=y9();if(b&&b.id==a.id){if(R8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))B9&&(B9.token=a),(b=z9())&&b.jB(a)}else b&&C9(),D9(a,1)}else z9()&&C9()},C9=function(){P8()?M8().stopSession():K8("stopSession called before API ready.");
var a=z9();a&&(a.disconnect(1),E9(null))},F9=function(){var a=z9();
return!!a&&3!=a.getProxyState()},t9=function(a){c8("remote",a)},r9=function(){if(!G9){var a=g.Ha("yt.mdx.remote.screenService_");
G9=a?new o9(a):null}return G9},s9=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},SYa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},TYa=function(){return g.Ha("yt.mdx.remote.connectData_")},v9=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},z9=function(){return g.Ha("yt.mdx.remote.connection_")},E9=function(a){var b=z9();
v9(null);a||SYa("");g.Ga("yt.mdx.remote.connection_",a,void 0);q9&&(g.qc(q9,function(c){c(a)}),q9.length=0);
b&&!a?b7("yt-remote-connection-change",!1):!b&&a&&b7("yt-remote-connection-change",!0)},w9=function(){var a=g.Ty();
if(!a)return null;var b=r9();if(!b)return null;b=b.Ih();return j7(b,a)},D9=function(a,b){s9();
y9()&&y9();if(H9)B9=a;else{SYa(a.id);var c=g.Ha("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new h9(p9,a,x9(),c);a.connect(b,TYa());a.subscribe("beforeDisconnect",function(d){b7("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){z9()&&(z9(),E9(null))});
a.subscribe("browserChannelAuthError",function(){var d=y9();d&&"shortLived"==d.idType&&(P8()?M8().handleBrowserChannelAuthError():K8("refreshLoungeToken called before API ready."))});
E9(a)}},OYa=function(){var a=w9();
a?(t9("Resume connection to: "+f7(a)),D9(a,0)):(o7(),sYa(),t9("Skipping connecting because no session screen found."))},MYa=function(){var a=x9();
if(g.Ve(a)){a=m7();var b=g.Ry("yt-remote-session-name")||"",c=g.Ry("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},x9=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},I9=function(a,b,c){g.G.call(this);
var d=this;this.u=a;this.J=b;this.Vb=c;this.events=new g.JC(this);this.Z=this.events.T(this.J,"onVolumeChange",function(e){UYa(d,e)});
this.D=!1;this.I=new g.qJ(64);this.i=new g.Q(this.tO,500,this);this.B=new g.Q(this.uO,1E3,this);this.S=new u7(this.wY,0,this);this.C={};this.X=new g.Q(this.cP,1E3,this);this.K=new v7(this.seekTo,1E3,this);this.oa=g.Ia;g.I(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.mV);this.events.T(b,"captionschanged",this.CU);this.events.T(b,"captionssettingschanged",this.AO);this.events.T(b,"videoplayerreset",this.CA);this.events.T(b,"mdxautoplaycancel",function(){d.Vb.pK()});
a=this.Vb;a.isDisposed();a.subscribe("proxyStateChange",this.iN,this);a.subscribe("remotePlayerChange",this.Pw,this);a.subscribe("remoteQueueChange",this.CA,this);a.subscribe("previousNextChange",this.fN,this);a.subscribe("nowAutoplaying",this.ZM,this);a.subscribe("autoplayDismissed",this.BM,this);g.I(this,this.i);g.I(this,this.B);g.I(this,this.S);g.I(this,this.X);g.I(this,this.K);this.AO();this.CA();this.Pw()},UYa=function(a,b){if(J9(a)){a.Vb.unsubscribe("remotePlayerChange",a.Pw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=a9(a.Vb);if(c!==d.volume||b!==d.muted)a.Vb.setVolume(c,b),a.X.start();a.Vb.subscribe("remotePlayerChange",a.Pw,a)}},VYa=function(a){a.Tb(0);
a.i.stop();a.Wb(new g.qJ(64))},K9=function(a,b){if(J9(a)&&!a.D){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.bf(c,b));a.Vb.HI(a.J.getVideoData(1).videoId,c);a.C=a9(a.Vb).trackData}},L9=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Vb.playVideo(c.videoId,b,d,e,c.playerParams,c.Za,sWa(c));a.Wb(new g.qJ(1))},WYa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{rL:1});
c&&c.length?(a.J.setOption("captions","track",b),a.D=!1):(a.J.loadModule("captions"),a.D=!0)}else a.J.setOption("captions","track",{})},J9=function(a){return a9(a.Vb).videoId===a.J.getVideoData(1).videoId},M9=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",va:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",va:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ja:["ytp-button","ytp-mdx-privacy-popup-cancel"],va:"Cancel"},{G:"button",Ja:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],va:"Confirm"}]}]}]});this.i=new g.WK(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},N9=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.ywa()]},{G:"div",L:"ytp-remote-display-status-text",va:"{{statustext}}"}]}]});this.api=a;this.i=new g.WK(this,250);g.I(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);XYa(this,a.Ab())},XYa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.T(b,128)?g.BH("Error on $RECEIVER_NAME",c):b.Hc()||g.T(b,4)?g.BH("Playing on $RECEIVER_NAME",c):g.BH("Connected to $RECEIVER_NAME",c);a.Pa("statustext",b);a.i.show()}else a.i.hide()},O9=function(a,b){g.wP.call(this,"Play on",0,a,b);
this.J=a;this.No={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},P9=function(a){g.DM.call(this,a);
this.Zk={key:h7(),name:"This computer"};this.ri=null;this.subscriptions=[];this.fG=this.Vb=null;this.No=[this.Zk];this.Bn=this.Zk;this.Dd=new g.qJ(64);this.QL=0;this.zf=-1;this.Xw=!1;this.Vw=this.Et=null;if(!g.tE(this.player.V())&&!g.uE(this.player.V())){a=this.player;var b=g.gM(a);b&&(b=b.Rn())&&(b=new O9(a,b),g.I(this,b));b=new N9(a);g.I(this,b);g.qM(a,b.element,4);this.Et=new M9;g.I(this,this.Et);g.qM(a,this.Et.element,4);this.Xw=!!w9()}},Q9=function(a){a.Vw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Vw),a.Vw=null)},YYa=function(a,b,c){a.Dd=c;
a.player.ea("presentingplayerstatechange",new g.kH(c,b))},R9=function(a,b){if(b.key!==a.Bn.key)if(b.key===a.Zk.key)C9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Xw||!a.Et);(c?0:g.JE(a.player.V())||g.ME(a.player.V()))&&ZYa(a);a.Bn=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.uE(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.xM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Za,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=sWa(c))&&(a.locationInfo=c)}t9("Connecting to: "+g.Ni(b));"cast-selector-receiver"==b.key?(v9(a||null),b=a||null,P8()?M8().setLaunchParams(b):K8("setLaunchParams called before ready.")):!a&&F9()&&
s9()==b.key?b7("yt-remote-connection-change",!0):(C9(),v9(a||null),a=r9().Ih(),(b=j7(a,b.key))&&D9(b,1))}}},ZYa=function(a){a.player.Ab().Hc()?a.player.pauseVideo():(a.Vw=function(b){!a.Xw&&g.mH(b,8)&&(a.player.pauseVideo(),Q9(a))},a.player.addEventListener("presentingplayerstatechange",a.Vw));
a.Et&&a.Et.yd();z9()||(H9=!0)},aXa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},H7={"'":"\\'"},yWa={RZ:"atp",xaa:"ska",d$:"que",T7:"mus",waa:"sus",V3:"dsp",B$:"seq",w7:"mic",O2:"dpa",g_:"cds",R7:"mlm",L2:"dsdtr"};c7.prototype.equals=function(a){return a?this.id==a.id:!1};
var p7,l7="",SWa=NWa("loadCastFramework")||NWa("loadCastApplicationFramework"),UWa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(u7,g.G);g.k=u7.prototype;g.k.bR=function(a){this.C=arguments;this.i=!1;this.Nb?this.B=g.Sa()+this.Wf:this.Nb=g.ei(this.D,this.Wf)};
g.k.stop=function(){this.Nb&&(g.C.clearTimeout(this.Nb),this.Nb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.I.apply(null,this.C)))};
g.k.ya=function(){this.stop();u7.me.ya.call(this)};
g.k.cR=function(){this.Nb&&(g.C.clearTimeout(this.Nb),this.Nb=null);this.B?(this.Nb=g.ei(this.D,this.B-g.Sa()),this.B=null):this.u?this.i=!0:(this.i=!1,this.I.apply(null,this.C))};g.v(v7,g.G);g.k=v7.prototype;g.k.BI=function(a){this.B=arguments;this.Nb||this.u?this.i=!0:w7(this)};
g.k.stop=function(){this.Nb&&(g.C.clearTimeout(this.Nb),this.Nb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Nb||(this.i=!1,w7(this))};
g.k.ya=function(){g.G.prototype.ya.call(this);this.stop()};x7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
x7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var z7=new g.tf;g.v(WWa,g.ye);g.k=B7.prototype;g.k.ip=null;g.k.Rm=!1;g.k.uu=null;g.k.zH=null;g.k.Jt=null;g.k.Xt=null;g.k.qn=null;g.k.Qo=null;g.k.Eq=null;g.k.Lf=null;g.k.JB=0;g.k.Xj=null;g.k.HB=null;g.k.cn=null;g.k.Ou=-1;g.k.gO=!0;g.k.Cp=!1;g.k.vC=0;g.k.XA=null;var ZWa={},E7={};g.k=B7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.dR=function(a){a=a.target;var b=this.XA;b&&3==g.uj(a)?b.BI():this.mP(a)};
g.k.mP=function(a){try{if(a==this.Lf)a:{var b=g.uj(this.Lf),c=this.Lf.u,d=this.Lf.getStatus();if(g.Gc&&!g.zc(10)||g.fh&&!g.yc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.zj(this.Lf))break a;this.Cp||4!=b||7==c||(8==c||0>=d?this.i.Lj(3):this.i.Lj(2));I7(this);var e=this.Lf.getStatus();this.Ou=e;var f=g.zj(this.Lf);if(this.Rm=200==e){4==b&&F7(this);if(this.D){for(a=!0;!this.Cp&&this.JB<f.length;){var h=$Wa(this,f);if(h==E7){4==b&&(this.cn=4,A7(15),a=!1);break}else if(h==ZWa){this.cn=4;A7(16);a=!1;
break}else J7(this,h)}4==b&&0==f.length&&(this.cn=1,A7(17),a=!1);this.Rm=this.Rm&&a;a||(F7(this),G7(this))}else J7(this,f);this.Rm&&!this.Cp&&(4==b?this.i.py(this):(this.Rm=!1,D7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.cn=3,A7(13)):(this.cn=0,A7(14)),F7(this),G7(this)}}catch(l){this.Lf&&g.zj(this.Lf)}finally{}};
g.k.UW=function(a){y7((0,g.E)(this.TW,this,a),0)};
g.k.TW=function(a){this.Cp||(I7(this),J7(this,a),D7(this))};
g.k.qN=function(a){y7((0,g.E)(this.SW,this,a),0)};
g.k.SW=function(a){this.Cp||(F7(this),this.Rm=a,this.i.py(this),this.i.Lj(4))};
g.k.cancel=function(){this.Cp=!0;F7(this)};
g.k.bX=function(){this.uu=null;var a=Date.now();0<=a-this.zH?(2!=this.Xt&&this.i.Lj(3),F7(this),this.cn=2,A7(18),G7(this)):cXa(this,this.zH-a)};
g.k.getLastError=function(){return this.cn};g.k=fXa.prototype;g.k.wC=null;g.k.uh=null;g.k.YA=!1;g.k.vO=null;g.k.cz=null;g.k.aF=null;g.k.xC=null;g.k.ji=null;g.k.El=-1;g.k.Pu=null;g.k.Yu=null;g.k.connect=function(a){this.xC=a;a=L7(this.i,null,this.xC);A7(3);this.vO=Date.now();var b=this.i.S;null!=b?(this.Pu=b[0],(this.Yu=b[1])?(this.ji=1,gXa(this)):(this.ji=2,N7(this))):(Z6(a,"MODE","init"),this.uh=new B7(this,void 0,void 0,void 0),this.uh.ip=this.wC,C7(this.uh,a,!1,null,!0),this.ji=0)};
g.k.PR=function(a){if(a)this.ji=2,N7(this);else{A7(4);var b=this.i;b.qk=b.yn.El;U7(b,9)}a&&this.Lj(2)};
g.k.FD=function(a){return this.i.FD(a)};
g.k.abort=function(){this.uh&&(this.uh.cancel(),this.uh=null);this.El=-1};
g.k.vf=function(){return!1};
g.k.jN=function(a,b){this.El=a.Ou;if(0==this.ji)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.qk=this.El;U7(a,2);return}this.Pu=c[0];this.Yu=c[1]}else a=this.i,a.qk=this.El,U7(a,2);else if(2==this.ji)if(this.YA)A7(7),this.aF=Date.now();else if("11111"==b){if(A7(6),this.YA=!0,this.cz=Date.now(),a=this.cz-this.vO,!g.Gc||g.zc(10)||500>a)this.El=200,this.uh.cancel(),A7(12),M7(this.i,this,!0)}else A7(8),this.cz=this.aF=Date.now(),this.YA=!1};
g.k.py=function(){this.El=this.uh.Ou;if(this.uh.Rm)0==this.ji?this.Yu?(this.ji=1,gXa(this)):(this.ji=2,N7(this)):2==this.ji&&((!g.Gc||g.zc(10)?!this.YA:200>this.aF-this.cz)?(A7(11),M7(this.i,this,!1)):(A7(12),M7(this.i,this,!0)));else{0==this.ji?A7(9):2==this.ji&&A7(10);var a=this.i;this.uh.getLastError();a.qk=this.El;U7(a,2)}};
g.k.yx=function(){return this.i.yx()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Lj=function(a){this.i.Lj(a)};g.k=O7.prototype;g.k.pk=null;g.k.Fv=null;g.k.Xg=null;g.k.Me=null;g.k.yC=null;g.k.ez=null;g.k.DJ=null;g.k.qy=null;g.k.Cw=0;g.k.TT=0;g.k.Mf=null;g.k.Jn=null;g.k.Ol=null;g.k.Lp=null;g.k.yn=null;g.k.FB=null;g.k.Zs=-1;g.k.PL=-1;g.k.qk=-1;g.k.Es=0;g.k.Yr=0;g.k.Dp=8;g.Ta(iXa,g.ye);g.Ta(jXa,g.ye);g.k=O7.prototype;g.k.connect=function(a,b,c,d,e){A7(0);this.yC=b;this.Fv=c||{};d&&void 0!==e&&(this.Fv.OSID=d,this.Fv.OAID=e);this.I?(y7((0,g.E)(this.ZJ,this,a),100),nXa(this)):this.ZJ(a)};
g.k.ZJ=function(a){this.yn=new fXa(this);this.yn.wC=this.pk;this.yn.u=this.D;this.yn.connect(a)};
g.k.vf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.oN=function(a){this.Jn=null;rXa(this,a)};
g.k.nN=function(){this.Ol=null;this.Me=new B7(this,this.B,"rpc",this.K);this.Me.ip=this.pk;this.Me.vC=0;var a=this.DJ.clone();g.ml(a,"RID","rpc");g.ml(a,"SID",this.B);g.ml(a,"CI",this.FB?"0":"1");g.ml(a,"AID",this.Zs);P7(this,a);if(!g.Gc||g.zc(10))g.ml(a,"TYPE","xmlhttp"),C7(this.Me,a,!0,this.qy,!1);else{g.ml(a,"TYPE","html");var b=this.Me,c=!!this.qy;b.Xt=3;b.qn=Y6(a.clone());bXa(b,c)}};
g.k.jN=function(a,b){if(0!=this.i&&(this.Me==a||this.Xg==a))if(this.qk=a.Ou,this.Xg==a&&3==this.i)if(7<this.Dp){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Ol){if(this.Me)if(this.Me.Jt+3E3<this.Xg.Jt)R7(this),this.Me.cancel(),this.Me=null;else break a;T7(this);A7(19)}}else this.PL=a[1],0<this.PL-this.Zs&&37500>a[2]&&this.FB&&0==this.Yr&&!this.Lp&&(this.Lp=y7((0,g.E)(this.zU,this),6E3));else U7(this,11)}else null!=b&&U7(this,11);else if(this.Me==
a&&R7(this),!g.eb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Zs=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.qy=c[2],c=c[3],null!=c?this.Dp=c:this.Dp=6,this.i=3,this.Mf&&this.Mf.VJ(),this.DJ=L7(this,this.yx()?this.qy:null,this.yC),sXa(this)):"stop"==c[0]&&U7(this,7):3==this.i&&("stop"==c[0]?U7(this,7):"noop"!=c[0]&&this.Mf&&this.Mf.UJ(c),this.Yr=0)};
g.k.zU=function(){null!=this.Lp&&(this.Lp=null,this.Me.cancel(),this.Me=null,T7(this),A7(20))};
g.k.py=function(a){if(this.Me==a){R7(this);this.Me=null;var b=2}else if(this.Xg==a)this.Xg=null,b=1;else return;this.qk=a.Ou;if(0!=this.i)if(a.Rm)if(1==b){b=Date.now()-a.Jt;var c=z7;c.dispatchEvent(new iXa(c,a.Eq?a.Eq.length:0,b,this.Es));Q7(this);this.C.length=0}else sXa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.qk)){if(d=1==b)this.Xg||this.Jn||1==this.i||2<=this.Es?d=!1:(this.Jn=y7((0,g.E)(this.oN,this,a),tXa(this,this.Es)),this.Es++,d=!0);d=!(d||2==b&&T7(this))}if(d)switch(c){case 1:U7(this,
5);break;case 4:U7(this,10);break;case 3:U7(this,6);break;case 7:U7(this,12);break;default:U7(this,2)}}};
g.k.oS=function(a){if(!g.Zb(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.eY=function(a){a?A7(2):(A7(1),uXa(this,8))};
g.k.FD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.oj;a.S=!1;return a};
g.k.isActive=function(){return!!this.Mf&&this.Mf.isActive(this)};
g.k.Lj=function(a){var b=z7;b.dispatchEvent(new jXa(b,a))};
g.k.yx=function(){return!(!g.Gc||g.zc(10))};
g.k=vXa.prototype;g.k.VJ=function(){};
g.k.UJ=function(){};
g.k.TJ=function(){};
g.k.rD=function(){};
g.k.GK=function(){return{}};
g.k.isActive=function(){return!0};g.k=wXa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.Zb(this.i,a)||g.Zb(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.nQa)(b,a);0<=c?(g.bc(b,c),b=!0):b=!1;return b||g.cc(this.u,a)};
g.k.Di=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(V7,g.G);g.k=V7.prototype;g.k.LW=function(){this.Wf=Math.min(3E5,2*this.Wf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Wf+15E3*Math.random();g.$w(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Wf=5E3};g.Ta(W7,vXa);g.k=W7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.fg=function(a){return this.B.fg(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.Z||(this.Z=!0,g.ve(this.B),zXa(this),g.ve(this.u),this.u=null,this.oa=function(){return""})};
g.k.isDisposed=function(){return this.Z};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new O7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Mf=null);d.Mf=this;this.i=d;X7(this);if(this.i){d=g.L("ID_TOKEN");var f=this.i.pk||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.pk=f}e?(3!=e.getState()&&0==pXa(e)||e.getState(),this.i.connect(a,b,this.I,e.B,e.Zs)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.bf(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):Y7(this)&&(X7(this),oXa(this.i,a))};
g.k.VJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)oXa(this.i,a[b])}this.ea("handlerOpened")};
g.k.TJ=function(a){var b=2==a&&401==this.i.qk;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.rD=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.GK=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.bf(a,this.D);return a};
g.k.UJ=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),mXa(this.i)):this.ea("handlerMessage",new xXa(a[0],a[1]))};
g.k.jB=function(a){(this.I.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.pk||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.pk=b}};
g.k.GX=function(){this.u.isActive();0==pXa(this.i)&&this.connect(this.D,this.C)};Z7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z7.prototype.D=function(a){a(Error("request timed out"))};var GXa=Date.now(),b8=null,e8=Array(50),d8=-1,f8=!1;g.Ta(g8,g.ky);g8.prototype.Ih=function(){return this.screens};
g8.prototype.contains=function(a){return!!i7(this.screens,a)};
g8.prototype.get=function(a){return a?j7(this.screens,a):null};
g8.prototype.info=function(a){c8(this.I,a)};g.v(h8,g.ky);g.k=h8.prototype;g.k.start=function(){!this.i&&isNaN(this.Nb)&&this.AN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Nb)||(g.Ss(this.Nb),this.Nb=NaN)};
g.k.ya=function(){this.stop();g.ky.prototype.ya.call(this)};
g.k.AN=function(){this.Nb=NaN;this.i=g.Lt($7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.E)(this.fR,this),onError:(0,g.E)(this.eR,this),onTimeout:(0,g.E)(this.gR,this)})};
g.k.fR=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.I;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new d7(a),b)};
g.k.eR=function(a){this.i=null;a.status&&404==a.status?this.u>=$Ya.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=$Ya[this.u],this.Nb=g.Qs((0,g.E)(this.AN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.gR=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var $Ya=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(j8,g8);g.k=j8.prototype;g.k.start=function(){i8(this)&&this.ea("screenChange");!g.Ry("yt-remote-lounge-token-expiration")&&KXa(this);g.Ss(this.i);this.i=g.Qs((0,g.E)(this.start,this),1E4)};
g.k.add=function(a,b){i8(this);HXa(this,a);k8(this,!1);this.ea("screenChange");b(a);a.token||KXa(this)};
g.k.remove=function(a,b){var c=i8(this);JXa(this,a)&&(k8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.DB=function(a,b,c,d){var e=i8(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.ya=function(){g.Ss(this.i);j8.me.ya.call(this)};
g.k.PS=function(a){i8(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k8(this,!b);b&&c8(this.I,"Missed "+b+" lounge tokens.")};
g.k.OS=function(a){c8(this.I,"Requesting lounge tokens failed: "+a)};g.v(m8,g.ky);g.k=m8.prototype;g.k.start=function(){var a=parseInt(g.Ry("yt-remote-fast-check-period")||"0",10);(this.C=g.Sa()-144E5<a?0:a)?p8(this):(this.C=g.Sa()+3E5,g.Qy("yt-remote-fast-check-period",this.C),this.rG())};
g.k.isEmpty=function(){return g.Ve(this.i)};
g.k.update=function(){l8("Updating availability on schedule.");var a=this.I(),b=g.Je(this.i,function(c,d){return c&&!!j7(a,d)},this);
o8(this,b)};
g.k.ya=function(){g.Ss(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.ky.prototype.ya.call(this)};
g.k.rG=function(){g.Ss(this.B);this.B=NaN;this.u&&this.u.abort();var a=MXa(this);if($6(a)){var b=$7(this.D,"/pairing/get_screen_availability");this.u=a8(this.D,b,{lounge_token:g.Qe(a).join(",")},(0,g.E)(this.pW,this,a),(0,g.E)(this.oW,this))}else o8(this,{}),p8(this)};
g.k.pW=function(a,b){this.u=null;var c=g.Qe(MXa(this));if(g.oc(c,g.Qe(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;o8(this,c);p8(this)}else this.oe("Changing Screen set during request."),this.rG()};
g.k.oW=function(a){this.oe("Screen availability failed: "+a);this.u=null;p8(this)};
g.k.oe=function(a){c8("OnlineScreenService",a)};g.Ta(q8,g8);g.k=q8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.DB=function(a,b,c,d){this.u.contains(a)?this.u.DB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c8(this.I,a),d(Error(a)))};
g.k.Ih=function(a){return a?this.screens:g.ec(this.screens,g.hq(this.B,function(b){return!this.contains(b)},this))};
g.k.CI=function(){return g.hq(this.Ih(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.DI=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new h8(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.ve(l);e(r8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.ve(l);f(m)});
l.start();return(0,g.E)(l.stop,l)};
g.k.hR=function(a,b,c,d){g.Lt($7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.E)(function(e,f){e=new d7(f.screen||{});if(!e.name||QXa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);QXa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(r8(this,e))},this),
onError:(0,g.E)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.E)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ya=function(){g.ve(this.u);g.ve(this.i);q8.me.ya.call(this)};
g.k.ZS=function(){SXa(this);this.ea("screenChange");this.i.update()};
q8.prototype.dispose=q8.prototype.dispose;g.Ta(t8,g.ky);g.k=t8.prototype;g.k.getScreen=function(){return this.C};
g.k.Ag=function(a){this.isDisposed()||(a&&(v8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){c8(this.Ba,a)};
g.k.FI=function(){return null};
g.k.GG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.E)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.E)(function(){v8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ya=function(){this.GG("");t8.me.ya.call(this)};g.v(w8,t8);g.k=w8.prototype;g.k.FG=function(a){if(this.u){if(this.u==a)return;v8(this,"Overriding cast session with new session object");aYa(this);this.xa=!1;this.X="unknown";this.u.removeUpdateListener(this.oa);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.oa);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);XXa(this,"getMdxSessionStatus")};
g.k.gt=function(a){this.info("launchWithParams no-op for Cast: "+g.Ni(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.E)(function(){this.Ag()},this),(0,g.E)(function(){this.Ag(Error("Failed to stop receiver app."))},this)):this.Ag(Error("Stopping cast device without session."))};
g.k.GG=function(){};
g.k.ya=function(){this.info("disposeInternal");aYa(this);this.u&&(this.u.removeUpdateListener(this.oa),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;t8.prototype.ya.call(this)};
g.k.fX=function(a,b){if(!this.isDisposed())if(b)if(b=a7(b),g.Na(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Ni(b)),a){case "mdxSessionStatus":VXa(this,b);break;case "loungeToken":YXa(this,b);break;default:v8(this,"Unknown youtube message: "+a)}else v8(this,"Unable to parse message.");else v8(this,"No data in message.")};
g.k.UK=function(a,b,c,d){g.Ss(this.S);this.S=0;PXa(this.B,this.i.label,a,this.i.friendlyName,(0,g.E)(function(e){e?b(e):0<=d?(v8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.Qs((0,g.E)(this.UK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.FI=function(){return this.u};
g.k.iR=function(a){this.isDisposed()||a||(v8(this,"Cast session died."),this.Ag())};g.v(z8,t8);g.k=z8.prototype;g.k.FG=function(a){this.u=a;this.u.addUpdateListener(this.Ia)};
g.k.gt=function(a){this.Ka=a;this.Z()};
g.k.stop=function(){hYa(this);this.u?this.u.stop((0,g.E)(this.Ag,this,null),(0,g.E)(this.Ag,this,"Failed to stop DIAL device.")):this.Ag()};
g.k.ya=function(){hYa(this);this.u&&this.u.removeUpdateListener(this.Ia);this.u=null;t8.prototype.ya.call(this)};
g.k.jR=function(a){this.isDisposed()||a||(v8(this,"DIAL session died."),this.D(),this.D=g.Ia,this.Ag())};g.v(D8,t8);D8.prototype.stop=function(){this.Ag()};
D8.prototype.FG=function(){};
D8.prototype.gt=function(){g.Ss(this.u);this.u=NaN;var a=j7(this.B.Ih(),this.i.label);a?u8(this,a):this.Ag(Error("No such screen"))};
D8.prototype.ya=function(){g.Ss(this.u);this.u=NaN;t8.prototype.ya.call(this)};g.v(E8,g.ky);g.k=E8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.I?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.E)(this.aW,this);c=new chrome.cast.ApiConfig(c,(0,g.E)(this.kN,this),e,d,a);c.customDialLaunchCallback=(0,g.E)(this.UU,this);
chrome.cast.initialize(c,(0,g.E)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),DXa(),this.u.subscribe("onlineScreenChange",(0,g.E)(this.GI,this)),this.B=kYa(this),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(f){this.oe("Failed to set initial custom receivers: "+g.Ni(f))},this)),this.ea("yt-remote-cast2-availability-change",G8(this)),b(!0))},this),(0,g.E)(function(f){this.oe("Failed to initialize API: "+g.Ni(f));
b(!1)},this))};
g.k.KX=function(a,b){F8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)F8("Unsetting old screen status: "+this.i.i.friendlyName),H8(this,null)}if(a&&b){if(!this.i){c=j7(this.u.Ih(),a);if(!c){F8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){F8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=iYa(this,c);a||(F8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(d){this.oe("Failed to set initial custom receivers: "+g.Ni(d))},this)));
F8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);H8(this,new D8(this.u,a),!0)}this.i.GG(b)}else F8("setConnectedScreenStatus: no screen.")};
g.k.LX=function(a){this.isDisposed()?this.oe("Setting connection data on disposed cast v2"):this.i?this.i.gt(a):this.oe("Setting connection data without a session")};
g.k.lR=function(){this.isDisposed()?this.oe("Stopping session on disposed cast v2"):this.i?(this.i.stop(),H8(this,null)):F8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.E)(this.kN,this),(0,g.E)(this.sW,this))};
g.k.ya=function(){this.u.unsubscribe("onlineScreenChange",(0,g.E)(this.GI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=AXa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.cc(b||[],a);g.ve(this.i);g.ky.prototype.ya.call(this)};
g.k.oe=function(a){c8("Controller",a)};
g.k.mN=function(a,b){this.i==a&&(b||H8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.XV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)F8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{F8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H8(this,
new D8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H8(this,new z8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:H8(this,new w8(this.u,a,this.config_));break;default:this.oe("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.oe("Stopping receiver w/o session: "+a.friendlyName)}else this.oe("onReceiverAction_ called without receiver.")};
g.k.UU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.oe("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.oe("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return F8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.oe('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H8(this,new z8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,A8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=eYa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Bs(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=fYa(b,c)):a=fYa(b,c)):a=C8(b);return a};
g.k.kN=function(a){var b=this;if(!this.isDisposed()&&!this.I){F8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)F8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),H8(this,new w8(this.u,c,this.config_),!0);else{this.oe("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=j7(this.u.Ih(),
d.label);e&&e7(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(F8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.ve(this.i),this.i=new w8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.E)(this.mN,this,this.i)),this.i.subscribe("sessionFailed",function(){return jYa(b,b.i)}),this.i.gt(null));
this.i.FG(a)}}};
g.k.kR=function(){return this.i?this.i.FI():null};
g.k.sW=function(a){this.isDisposed()||(this.oe("Failed to estabilish a session: "+g.Ni(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.aW=function(a){F8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=G8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;G8(this)!=b&&this.ea("yt-remote-cast2-availability-change",G8(this))}};
g.k.GI=function(){this.isDisposed()||(this.B=kYa(this),F8("Updating custom receivers: "+g.Ni(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(){this.oe("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",G8(this)))};
E8.prototype.setLaunchParams=E8.prototype.LX;E8.prototype.setConnectedScreenStatus=E8.prototype.KX;E8.prototype.stopSession=E8.prototype.lR;E8.prototype.getCastSession=E8.prototype.kR;E8.prototype.requestSession=E8.prototype.requestSession;E8.prototype.init=E8.prototype.init;E8.prototype.dispose=E8.prototype.dispose;var N8=[];g.k=S8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Rk=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Hc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Tj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+U8(this):this.D};
g.k.clone=function(){return new S8(Y8(this))};g.v($8,g.ky);g.k=$8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){b9(this)?(this.i?this.i.play(null,g.Ia,g9(this,"play")):f9(this,"play"),e9(this,1,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.play)};
g.k.pause=function(){b9(this)?(this.i?this.i.pause(null,g.Ia,g9(this,"pause")):f9(this,"pause"),e9(this,2,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.pause)};
g.k.seekTo=function(a){if(b9(this)){if(this.i){var b=a9(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Hc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,g9(this,"seekTo",{newTime:a}))}else f9(this,"seekTo",{newTime:a});e9(this,3,a);this.ea("remotePlayerChange")}else c9(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(b9(this)){this.i?this.i.stop(null,g.Ia,g9(this,"stopVideo")):f9(this,"stopVideo");var a=a9(this);a.index=-1;a.videoId="";T8(a);d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.stop)};
g.k.setVolume=function(a,b){if(b9(this)){var c=a9(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.E)(function(){c8("CP","set receiver volume: "+d)},this),(0,g.E)(function(){this.oe("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.E)(function(){c8("CP","set receiver muted: "+b)},this),(0,g.E)(function(){this.oe("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f9(this,"setVolume",e)}c.muted=b;c.volume=a;d9(this,c)}else c9(this,g.Qa(this.setVolume,a,b))};
g.k.HI=function(a,b){if(b9(this)){var c=a9(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Ni(b.style),g.bf(a,c.trackData));f9(this,"setSubtitlesTrack",a);d9(this,c)}else c9(this,g.Qa(this.HI,a,b))};
g.k.setAudioTrack=function(a,b){b9(this)?(b=b.getLanguageInfo().getId(),f9(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=a9(this),a.audioTrackId=b,d9(this,a)):c9(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=a9(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);X8(l,a,c||0);void 0!==b&&(V8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Ni(h));f9(this,"setPlaylist",m);d||d9(this,l)};
g.k.QA=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"previous")}else c9(this,g.Qa(this.QA,a,b))};
g.k.nextVideo=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"next")}else c9(this,g.Qa(this.nextVideo,a,b))};
g.k.hs=function(){if(b9(this)){f9(this,"clearPlaylist");var a=a9(this);a.reset();d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.hs)};
g.k.pK=function(){b9(this)?f9(this,"dismissAutoplay"):c9(this,this.pK)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.ky.prototype.dispose.call(this)};
g.k.ya=function(){wYa(this);this.C=null;this.D.clear();Z8(this,null);g.ky.prototype.ya.call(this)};
g.k.HG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.VV=function(a,b){this.ea(a,b)};
g.k.FU=function(a){if(!a)this.Lw(null),Z8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=a9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c8("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d9(this,b)}};
g.k.Lw=function(a){c8("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),xYa(this),this.ea("remotePlayerChange")};
g.k.EU=function(a){a?(xYa(this),this.ea("remotePlayerChange")):this.Lw(null)};
g.k.dH=function(){f9(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.MU=function(){var a=tYa();a&&Z8(this,a)};
g.k.oe=function(a){c8("CP",a)};g.v(h9,g.ky);g.k=h9.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.wc.listId=c);this.wc.videoId=d;this.wc.index=l||0;this.wc.state=3;V8(this.wc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";i9("Connecting with "+c+" and params: "+g.Ni(m));this.i.connect({method:c,params:g.Ni(m)},a,GWa())}else i9("Connecting without params"),this.i.connect({},a,GWa());AYa(this)};
g.k.jB=function(a){this.i.jB(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ga("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),j9(this,3));g.ky.prototype.dispose.call(this)};
g.k.ya=function(){k9(this);m9(this);l9(this);g.Ss(this.K);this.K=NaN;g.Ss(this.S);this.S=NaN;this.B=null;g.Hs(this.X);this.X.length=0;this.i.dispose();g.ky.prototype.ya.call(this);this.C=this.I=this.u=this.wc=this.i=null};
g.k.KS=function(){this.As(2)};
g.k.JU=function(){i9("Channel opened");this.xa&&(this.xa=!1,l9(this),this.oa=g.Qs((0,g.E)(function(){i9("Timing out waiting for a screen.");this.As(1)},this),15E3));
KWa(yXa(this.i),this.Ka)};
g.k.GU=function(){i9("Channel closed");isNaN(this.D)?o7(!0):o7();this.dispose()};
g.k.HU=function(a,b){o7();isNaN(this.Uv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),i9("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,i9("Channel error: "+a+" with reconnection in "+this.Uv()+" ms"),j9(this,2))};
g.k.zL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.q(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.IU=function(a){a.params?i9("Received: action="+a.action+", params="+g.Ni(a.params)):i9("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=a7(a.params.devices);this.u=g.Un(a,function(c){return new c7(c)});
a=!!g.Vb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
DYa(this,a);a=this.zL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.dc(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
DYa(this,!1);break;case "remoteConnected":var b=new c7(a7(a.params.device));g.Vb(this.u,function(c){return c.equals(b)})||tWa(this.u,b);
break;case "remoteDisconnected":b=new c7(a7(a.params.device));g.dc(this.u,function(c){return c.equals(b)});
break;case "gracefulDisconnect":break;case "playlistModified":FYa(this,a,"QUEUE_MODIFIED");break;case "nowPlaying":HYa(this,a);break;case "onStateChange":GYa(this,a);break;case "onAdStateChange":IYa(this,a);break;case "onVolumeChanged":JYa(this,a);break;case "onSubtitlesTrackChanged":EYa(this,a);break;case "nowAutoplaying":KYa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.ea("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":LYa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:i9("Unrecognized action: "+a.action)}};
g.k.AX=function(){if(this.B){var a=this.B;this.B=null;this.wc.videoId!=a&&n9(this,"getNowPlaying")}};
g.k.HS=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Uv())?Y7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.As=function(a){i9("Disconnecting with "+a);g.Ga("yt.mdx.remote.remoteClient_",null,void 0);k9(this);this.ea("beforeDisconnect",a);1==a&&o7();zXa(this.i,a);this.dispose()};
g.k.ES=function(){var a=this.wc;this.B&&(a=this.wc.clone(),X8(a,this.B,a.index));return Y8(a)};
g.k.MX=function(a){var b=new S8(a);b.videoId&&b.videoId!=this.wc.videoId&&(this.B=b.videoId,g.Ss(this.K),this.K=g.Qs((0,g.E)(this.AX,this),5E3));var c=[];this.wc.listId==b.listId&&this.wc.videoId==b.videoId&&this.wc.index==b.index||c.push("remoteQueueChange");this.wc.playerState==b.playerState&&this.wc.volume==b.volume&&this.wc.muted==b.muted&&W8(this.wc)==W8(b)&&g.Ni(this.wc.trackData)==g.Ni(b.trackData)||c.push("remotePlayerChange");this.wc.reset(a);g.qc(c,function(d){this.ea(d)},this)};
g.k.TK=function(){var a=this.i.I.id,b=g.Vb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Uv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.BS=function(){return this.C||"UNSUPPORTED"};
g.k.CS=function(){return this.I||""};
g.k.mR=function(){if(!isNaN(this.Uv())){var a=this.i.u;g.ax(a.i);a.start()}};
g.k.JX=function(a,b){n9(this,a,b);CYa(this)};
g.k.II=function(){var a=g.Ku("SID","")||"",b=g.Ku("SAPISID","")||"",c=g.Ku("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.Cc(g.bb(a),2);b=g.Cc(g.bb(b),2);c=g.Cc(g.bb(c),2);return g.Cc(g.bb(a+","+b+","+c),2)};
h9.prototype.subscribe=h9.prototype.subscribe;h9.prototype.unsubscribeByKey=h9.prototype.fg;h9.prototype.getProxyState=h9.prototype.HS;h9.prototype.disconnect=h9.prototype.As;h9.prototype.getPlayerContextData=h9.prototype.ES;h9.prototype.setPlayerContextData=h9.prototype.MX;h9.prototype.getOtherConnectedRemoteId=h9.prototype.TK;h9.prototype.getReconnectTimeout=h9.prototype.Uv;h9.prototype.getAutoplayMode=h9.prototype.BS;h9.prototype.getAutoplayVideoId=h9.prototype.CS;h9.prototype.reconnect=h9.prototype.mR;
h9.prototype.sendMessage=h9.prototype.JX;h9.prototype.getXsrfToken=h9.prototype.II;h9.prototype.isCapabilitySupportedOnConnectedDevices=h9.prototype.zL;g.v(o9,g8);g.k=o9.prototype;g.k.Ih=function(a){return this.Ue.$_gs(a)};
g.k.contains=function(a){return!!this.Ue.$_c(a)};
g.k.get=function(a){return this.Ue.$_g(a)};
g.k.start=function(){this.Ue.$_st()};
g.k.add=function(a,b,c){this.Ue.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ue.$_r(a,b,c)};
g.k.DB=function(a,b,c,d){this.Ue.$_un(a,b,c,d)};
g.k.ya=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ue.$_ubk(this.i[a]);this.i.length=0;this.Ue=null;g8.prototype.ya.call(this)};
g.k.nR=function(){this.ea("screenChange")};
g.k.BV=function(){this.ea("onlineScreenChange")};
q8.prototype.$_st=q8.prototype.start;q8.prototype.$_gspc=q8.prototype.hR;q8.prototype.$_gsppc=q8.prototype.DI;q8.prototype.$_c=q8.prototype.contains;q8.prototype.$_g=q8.prototype.get;q8.prototype.$_a=q8.prototype.add;q8.prototype.$_un=q8.prototype.DB;q8.prototype.$_r=q8.prototype.remove;q8.prototype.$_gs=q8.prototype.Ih;q8.prototype.$_gos=q8.prototype.CI;q8.prototype.$_s=q8.prototype.subscribe;q8.prototype.$_ubk=q8.prototype.fg;var B9=null,H9=!1,p9=null,q9=null,G9=null,u9=[];g.v(I9,g.G);g.k=I9.prototype;g.k.ya=function(){g.G.prototype.ya.call(this);this.i.stop();this.B.stop();this.S.stop();this.oa();var a=this.Vb;a.unsubscribe("proxyStateChange",this.iN,this);a.unsubscribe("remotePlayerChange",this.Pw,this);a.unsubscribe("remoteQueueChange",this.CA,this);a.unsubscribe("previousNextChange",this.fN,this);a.unsubscribe("nowAutoplaying",this.ZM,this);a.unsubscribe("autoplayDismissed",this.BM,this);this.Vb=this.u=null};
g.k.Dj=function(a){var b=g.Aa.apply(1,arguments);if(2!=this.Vb.B)if(J9(this)){var c=a;if(!a9(this.Vb).isAdPlaying()||"control_seek"!==c)switch(c){case "control_toggle_play_pause":a9(this.Vb).Hc()?this.Vb.pause():this.Vb.play();break;case "control_play":this.Vb.play();break;case "control_pause":this.Vb.pause();break;case "control_seek":this.K.BI(b[0],b[1]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":b=
this.J.getCurrentTime();L9(this,0===b?void 0:b);break;case "control_seek":L9(this,b[0]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}};
g.k.CU=function(a){this.S.bR(a)};
g.k.wY=function(a){this.Dj("control_subtitles_set_track",g.Ve(a)?null:a)};
g.k.AO=function(){var a=this.J.getOption("captions","track");g.Ve(a)||K9(this,a)};
g.k.Tb=function(a){this.u.Tb(a,this.J.getVideoData().lengthSeconds)};
g.k.mV=function(){g.Ve(this.C)||WYa(this,this.C);this.D=!1};
g.k.iN=function(a,b){this.B.stop();2===b&&this.uO()};
g.k.Pw=function(){if(J9(this)){this.i.stop();var a=a9(this.Vb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.zf=1;break;case 1082:case 1083:this.u.zf=0;break;default:this.u.zf=-1}switch(a.playerState){case 1081:case 1:this.Wb(new g.qJ(8));this.tO();break;case 1085:case 3:this.Wb(new g.qJ(9));break;case 1083:case 0:this.Wb(new g.qJ(2));this.K.stop();this.Tb(this.J.getVideoData().lengthSeconds);break;case 1084:this.Wb(new g.qJ(4));break;case 2:this.Wb(new g.qJ(4));this.Tb(W8(a));
break;case -1:this.Wb(new g.qJ(64));break;case -1E3:this.Wb(new g.qJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a9(this.Vb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,WYa(this,a));a=a9(this.Vb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.X.isActive()||this.cP()}else VYa(this)};
g.k.fN=function(){this.J.ea("mdxpreviousnextchange")};
g.k.CA=function(){J9(this)||VYa(this)};
g.k.ZM=function(a){isNaN(a)||this.J.ea("mdxnowautoplaying",a)};
g.k.BM=function(){this.J.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J9(this)&&this.Vb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a9(this.Vb).playerState?L9(this,a):b&&this.Vb.seekTo(a)};
g.k.cP=function(){var a=this;if(J9(this)){var b=a9(this.Vb);this.events.xc(this.Z);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.Z=this.events.T(this.J,"onVolumeChange",function(c){UYa(a,c)})}};
g.k.tO=function(){this.i.stop();if(!this.Vb.isDisposed()){var a=a9(this.Vb);a.Hc()&&this.Wb(new g.qJ(8));this.Tb(W8(a));this.i.start()}};
g.k.uO=function(){this.B.stop();this.i.stop();var a=this.Vb.C.getReconnectTimeout();2==this.Vb.B&&!isNaN(a)&&this.B.start()};
g.k.Wb=function(a){this.B.stop();var b=this.I;if(!g.vJ(b,a)){var c=g.T(a,2);c!==g.T(this.I,2)&&this.J.Pt(c);this.I=a;YYa(this.u,b,a)}};g.v(M9,g.V);M9.prototype.yd=function(){this.i.show()};
M9.prototype.Db=function(){this.i.hide()};
M9.prototype.u=function(){b7("mdx-privacy-popup-cancel");this.Db()};
M9.prototype.B=function(){b7("mdx-privacy-popup-confirm");this.Db()};g.v(N9,g.V);N9.prototype.onStateChange=function(a){XYa(this,a.state)};g.v(O9,g.wP);O9.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.No=g.rc(a,this.i,this),g.xP(this,g.Un(a,this.i)),a=this.J.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.gi(a),this.enable(!0)):this.enable(!1)};
O9.prototype.i=function(a){return a.key};
O9.prototype.uj=function(a){return"cast-selector-receiver"===a?"Cast...":this.No[a].name};
O9.prototype.Df=function(a){g.wP.prototype.Df.call(this,a);this.J.setOption("remote","currentReceiver",this.No[a]);this.zb.Db()};g.v(P9,g.DM);g.k=P9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.rE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};PYa(b,a);this.subscriptions.push(g.fu("yt-remote-before-disconnect",this.BU,this));this.subscriptions.push(g.fu("yt-remote-connection-change",this.bW,this));this.subscriptions.push(g.fu("yt-remote-receiver-availability-change",this.hN,
this));this.subscriptions.push(g.fu("yt-remote-auto-connect",this.ZV,this));this.subscriptions.push(g.fu("yt-remote-receiver-resumed",this.YV,this));this.subscriptions.push(g.fu("mdx-privacy-popup-confirm",this.pX,this));this.subscriptions.push(g.fu("mdx-privacy-popup-cancel",this.oX,this));this.hN()};
g.k.load=function(){this.player.cancelPlayback();g.DM.prototype.load.call(this);this.ri=new I9(this,this.player,this.Vb);var a=(a=TYa())?a.currentTime:0;var b=F9()?new $8(z9(),void 0):null;0==a&&b&&(a=W8(a9(b)));0!==a&&this.Tb(a);YYa(this,this.Dd,this.Dd);this.player.ol(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.Bn=this.Zk;(0,g.we)(this.ri,this.Vb);this.Vb=this.ri=null;g.DM.prototype.unload.call(this);this.player.ol(5);Q9(this)};
g.k.ya=function(){g.gu(this.subscriptions);g.DM.prototype.ya.call(this)};
g.k.al=function(a){var b=g.Aa.apply(1,arguments);this.loaded&&this.ri.Dj.apply(this.ri,[a].concat(g.u(b)))};
g.k.getAdState=function(){return this.zf};
g.k.Rk=function(){return this.Vb?a9(this.Vb).Rk:!1};
g.k.hasNext=function(){return this.Vb?a9(this.Vb).hasNext:!1};
g.k.Tb=function(a,b){this.QL=a||0;this.player.ea("progresssync",a,b);this.player.Oa("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.QL};
g.k.getProgressState=function(){var a=a9(this.Vb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.wf():!a.isAdPlaying()&&this.player.wf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+U8(a):a.B,isAtLiveHead:1>=(a.u?a.i+U8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+U8(a):a.i,seekableStart:0<
a.C?a.C+U8(a):a.C}};
g.k.nextVideo=function(){this.Vb&&this.Vb.nextVideo()};
g.k.QA=function(){this.Vb&&this.Vb.QA()};
g.k.BU=function(a){1===a&&(this.fG=this.Vb?a9(this.Vb):null)};
g.k.bW=function(){var a=F9()?new $8(z9(),void 0):null;if(a){var b=this.Bn;this.loaded&&this.unload();this.Vb=a;this.fG=null;b.key!==this.Zk.key&&(this.Bn=b,this.load())}else(0,g.ve)(this.Vb),this.Vb=null,this.loaded&&(this.unload(),(a=this.fG)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.hN=function(){var a=[this.Zk],b=a.concat,c=QYa();O8()&&g.Ry("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.No=b.call(a,c);a=A9()||this.Zk;R9(this,a);this.player.Oa("onMdxReceiversChange")};
g.k.ZV=function(){var a=A9();R9(this,a)};
g.k.YV=function(){this.Bn=A9()};
g.k.pX=function(){this.Xw=!0;Q9(this);H9=!1;B9&&D9(B9,1);B9=null};
g.k.oX=function(){this.Xw=!1;Q9(this);R9(this,this.Zk);this.Bn=this.Zk;H9=!1;B9=null;this.player.playVideo()};
g.k.nf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.No;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q8():R9(this,b)),this.loaded?this.Bn:this.Zk;case "quickCast":return 2===this.No.length&&"cast-selector-receiver"===this.No[1].key?(b&&Q8(),!0):!1}};
g.k.dH=function(){this.Vb.dH()};
g.k.Yi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.CM("remote",P9);})(_yt_player);
