name: DeployMainToElasticBeanstalk

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-west-2"


    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1

      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      - run: java -version

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Maven package
        run: mvn --batch-mode --update-snapshots clean package -Dquarkus.package.type=uber-jar
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Pegar o ID do commit
        run: echo "${{github.sha}}"

      - name: Upload Jar to S3
        run: aws s3 cp tdc-api-eb.zip s3://artifacts.thedevconf/tdc-api-eb-v${{github.sha}}.zip
        working-directory: tdc-api/target

      - name: Criar a versao no EB
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name tdc-api \
            --version-label tdc-api-eb-v${{github.sha}} \
            --source-bundle S3Bucket="artifacts.thedevconf",S3Key="tdc-api-eb-v${{github.sha}}.zip"

      - name: Alterar o ambiente para a versao
        run: |
          aws elasticbeanstalk update-environment \
            --application-name tdc-api \
            --environment-name thedevconf-api-20210604 \
            --version-label tdc-api-eb-v${{github.sha}}


